### ISSUE TITLE
I get an error when trying to set up

### ISSUE THREAD

**Issue by 12nick12** [Yoda-x/ha-zha-new#15]
Here is my config
zha_new:
  usb_path: /dev/ttyUSB1
  database_path: /home/hass/.homeassistant/zigbee.db

 and here is the error i get https://imgur.com/a/K3h0I

**Comment by Yoda-x** [comment]
looks like you use HA>= 0.61. please try the the master-0.61plus branch.
I'm still on 0.60, thus, I not tested it. got the patch from @h3ndrik 
thanks

**Comment by Yoda-x** [comment]
Please reopen, if the master-0.61plus branch not works for you
