### ISSUE TITLE
Unable to pair more than 6 devices

### ISSUE THREAD

**Issue by tyler-vincent** [Yoda-x/ha-zha-new#24]
I can't seem to pair more than 6 devices. I noticed it after I'd paired a Sengled LED bulb and one of my Xiaomi temperature sensors stopped working. I removed the temperature sensor from the network by holding the button down till I saw three blinks, then tried adding it again but I never get the two blinks to indicate it's joined.

When I remove another device, I can add the temperature sensors again. It seems like I'm limited to 6 devices total. I have 3 Senled bulbs, a Xiaomi motion sensor, and two Xiaomi temperature sensors paired. I'm using the HUSBZB-1 combo USB stick.

When attempting to pair another device I get the following in the logs:
```
2018-03-22 03:50:03 WARNING (MainThread) [zigpy.application] Message on unknown device 0x0000
2018-03-22 03:50:04 WARNING (MainThread) [bellows.zigbee.application] Unexpected message send notification
2018-03-22 03:50:16 WARNING (MainThread) [zigpy.util] Error calling listener.zdo_command: zdo_command() missing 1 required positional argument: 'args'
```

The first two correlate with me setting `zha_new` to `permit` and the last seems to happen occasionally all the time. Otherwise I get no indication that a device is trying to pair. On the device itself I just get a single blink.

**Comment by tyler-vincent** [comment]
Also just in case I was having the same issue as before, I've verified I'm using your branches of `zigpy` and `bellows`

**Comment by walthowd** [comment]
I can confirm this behaviour. Using Home Assistant 0.65.4,  and Python 3.5.3 with latest zha-new.

 I also tried zigpy/bellows 0.51 with zigpy/zigpy 0.0.3 and your versions of zigpy and bellows. 

 I initially paired three Xiaomi door sensors, a Xiaomi body sensor, then paired three bulbs and could not pair another. I also saw the "Error calling listener.zdo_command: zdo_command() missing 1 required positional argument: 'args'"

**Comment by Yoda-x** [comment]
Hi 
can you double check you have my versions? did you call hass with the '--skip-pip' parameter?  You can switch to you virtual environment and do a "pip3 list"  .You should see my versions bellows 0.5.1-Y and zigpy 0.0.3.Y.
Do you have any devices that act as router? If possible, please shut them off and try again.
Thanks

**Comment by tyler-vincent** [comment]
Confirmed I'm using the correct versions of the libraries. `zigpy 0.0.3.Y` and `bellows 0.5.1-Y` in `pip3 list`. I don't think I have anything that acts as a router but I turned off the rest of the devices and tried pairing and got the same issue.

**Comment by Yoda-x** [comment]
ok,  can you enable debugging in the configuration yaml and send the debug file for the paring. 
Do you see something changing in the zha-new tile? 

Thanks

**Comment by walthowd** [comment]
I'm having trouble getting you good logs, as I've switched bellows/zigpy/zha versions around. Currently I am up to six paired bulbs and four Xiaomi sensors. 

When experiencing the issue, the zha tile does not change status from "permit"

RIght now I am getting re-occuring logs of "Error calling listener.zdo_command: zdo_command() missing 1 required positional argument: 'args'" but everything is working. When experiencing the issue, those logs that @tyler-vincent posted are displayed immediately after turning on the new pairing device. 

Only bug I can reproduce right now is when adding a bulb it gets added as light.sengled_e11g13_030c172f and light.sengled_e11g13_030c172f_1. The second entity responds to power commands and works as expected, the first entity is always displayed as on and doesn't respond to power commands. RSSI/LQI information is populated for both.

**Comment by Yoda-x** [comment]
ok, I pushed a new zha_new release with some bug fixes and a new feature. The double lights and listener warnings should be fixed. you may need to re-join the light, but try with the "update and restart" first. 
Please let me know if the problem with limited number of devices persist.

**Comment by walthowd** [comment]
I was able to join more bulbs without getting double lights, also can confirm the new availability checker is working for me, very cool new feature. I'm setting up another HA system soon and will report back if I can reliably reproduce the original issue.

**Comment by tyler-vincent** [comment]
So I _think_ this is working for me. When I initially installed it I wasn't able to pair any additional devices, but after removing and repairing a device I'm able to add more. I don't have any additional devices to test this, but I'm up to 7 devices now.

**Comment by Yoda-x** [comment]
with homeassistant 0.68 the the main bellows packet 0.5.2 has also the table patch
