### ISSUE TITLE
Trying to use zha_new with Hass.io v1.3 & Home Assistant 0.68.1

### ISSUE THREAD

**Issue by xtianpaiva** [Yoda-x/ha-zha-new#28]
Got this error message... any guidance?

> `Traceback (most recent call last):
  File "/config/custom_components/zha_new.py", line 355, in async_device_initialized
    populate_data()
  File "/config/custom_components/zha_new.py", line 80, in populate_data
    zha.DeviceType.COLOR_SCENE_CONTROLLER: 'binary_sensor'
  File "/usr/lib/python3.6/enum.py", line 324, in __getattr__
    raise AttributeError(name) from None
AttributeError: COLOR_SCENE_CONTROLLER`

**Comment by Yoda-x** [comment]
you have my versions of bellows and zigpy? I may have missed it in the readme, but they are mandatory.

**Comment by xtianpaiva** [comment]
Hi @Yoda-x , just got a new server Pi3 with Raspbian, since Hassio is not that flexible for testing.

Installled your bellows and zigpy:

`pip3 install git+https://github.com/Yoda-x/zigpy git+https://github.com/Yoda-x/bellows --user`

`Name: bellows
Version: 0.6.0-YD
Summary: Library implementing EZSP
Home-page: http://github.com/zigpy/bellows
Author: Russell Cloran
Author-email: rcloran@gmail.com
License: GPL-3.0
Location: /home/homeassistant/.local/lib/python3.5/site-packages
Requires: Click, click-log, pure-pcapy3, pyserial-asyncio, zigpy`

`Name: zigpy
Version: 0.1.0-Y
Summary: Library implementing a ZigBee stack
Home-page: http://github.com/zigpy/zigpy
Author: Russell Cloran
Author-email: rcloran@gmail.com
License: GPL-3.0
Location: /home/homeassistant/.local/lib/python3.5/site-packages
Requires: pycryptodome, crccheck`

But still get those errors trying to pair a Xiaomi Aqara door sensor:

`Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/homeassistant/.homeassistant/custom_components/zha_new.py", line 355, in async_device_initialized
    populate_data()
  File "/home/homeassistant/.homeassistant/custom_components/zha_new.py", line 80, in populate_data
    zha.DeviceType.COLOR_SCENE_CONTROLLER: 'binary_sensor'
  File "/usr/lib/python3.5/enum.py", line 274, in __getattr__
    raise AttributeError(name) from None
AttributeError: COLOR_SCENE_CONTROLLER
`

**Comment by xtianpaiva** [comment]
> Name: zigpy
Version: 0.1.0-Y
Summary: Library implementing a ZigBee stack
Home-page: http://github.com/zigpy/zigpy
Author: Russell Cloran
Author-email: rcloran@gmail.com
License: GPL-3.0
Location: /home/homeassistant/.local/lib/python3.5/site-packages
Requires: pycryptodome, crccheck

**Comment by Yoda-x** [comment]
I imported the upstream commits from rcloran. The quirks patch is not compatible with my code. I removed it again. please try now, if it works, and pull a fresh copy of my repo

**Comment by Yoda-x** [comment]
reopen if the problem persists
