### ISSUE TITLE
Bulbs go "unavailable" for a few seconds at a time, dozens of times per day.

### ISSUE THREAD

**Issue by wixoff** [Yoda-x/ha-zha-new#49]
I'm now using the Yoda-x zha-new software because it seems far more resilient than the original zha software, which had my devices simply dropping off, never to return.  (see zigpy/zigpy#78 and zigpy/bellows#124.)

But I'm still having some devices -- bulbs in particular -- become "Unavailable" for short times.

It varies from device to device, and even some Osram/Sylvania Lightify RGBW bulbs that are about 1 meter from the HUSBZB-1 stick have this problem.  A sample screenshot is attached (this "Office Table Lamp" is about 3m from the stick, 100% line-of-sight with only a clear glass lampshade in the way).

![img_6893-edited](https://user-images.githubusercontent.com/945097/45492896-76ddc900-b73b-11e8-942f-2844f40a2dca.jpg)

Each of those gray lines is an instance of "Unvavailable."  Could this even possibly be a software issue, or is it more likely WiFi interference or a bad USB stick?

I'm seeing this with both Osram/Sylvania Lightify and IKEA Tradfri bulbs.  However, my Iris/CentraLite outlet is solid as a rock - never unavailable, as far as the software tells me.

**Comment by Yoda-x** [comment]
Hi, I have this also for one of my bulbs, a  innr bulb. Still digging in it. It may a topology problem having too many hops in between, even if they are right beside. I have almost some kind of topology map ready, or to be  more accurate, it's deactivated right now. From what I see now, it's more about to configure the stick correctly or fine tune the network itself. 

One other point for discussion: makes it sense to set it to unavailable? It wanted to mark bulbs or wall plugs, that are shut off or disconnected. The drawback is, that you can't try to switch it, it's just unavailable in the UI.  It may be worth checking other options, like just showing a special icon, but keep it available

**Comment by wixoff** [comment]
Thanks.  I'd love to be able to see a topology map, in part because it's always mysterious to me when I fire up multiple bulbs at once, but one will delay turning on for like five seconds.

I think it's very useful to mark the state as unavailable -- at least for purposes of tracking state like in the card above.  Without it I wouldn't have seen this phenomenon.  And if a bulb stays unavailable for a while, I know there's something wrong.  (In the standard zha component, I would have to try the switch a few times to see that it's not responding -- it's not visible otherwise.)

But yes, the switch disappears during that time period and that's not ideal IMO.  Maybe keep the switch present and add an attribute to the entity?  Anyone who wants to could use a template to turn the attribute into a sensor (one problem with that is the attribute-based sensor would only update when the entity does, i.e. never when unavailable).

Or have two entities per device, light (for example) and sensor (e.g. health status).  The sensor, perhaps, would have a "health" of the device as its state (e.g. "good," "unavailable," "low link quality," etc.), with attributes showing the RF values like RSSI, LQI, etc.  Then those secondary attributes could be left out of the main entity/entities.  There would only need to be one health entity per device, even with multiple endpoints.  The Z-wave component does something quite similar - there's an entity per device that reports what the network status is.

**Comment by Yoda-x** [comment]
the new version is on  master with the topology map. have a look on wiki with an example
Looking to add a network status to the devices instead of making the unavailable.

**Comment by Yoda-x** [comment]
the next version will use the assumed states for this issue. the bulb will not show the toggle button durng the time the state is unclear. 
closing ticket
