### ISSUE TITLE
Cannot pair Xiaomi Aqara

### ISSUE THREAD

**Issue by darootler** [Yoda-x/ha-zha-new#67]
Hi!

I am using hassio, HA 0.84.6 and Elelabs ZigBee Raspberry Pi Shield. I am not able to pair the Xiaomi Aqara sensor. Here is the error:

```
2018-12-30 11:57:42 ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization: Message send failure messagesend timeout
Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/bellows/zigbee/application.py", line 349, in request
    v = await asyncio.wait_for(send_fut, timeout)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/zigpy/device.py", line 55, in _initialize
    epr = await self.zdo.request(0x0005, self.nwk, tries=3, delay=3)
  File "/config/deps/lib/python3.6/site-packages/zigpy/util.py", line 52, in retry
    r = await func()
  File "/config/deps/lib/python3.6/site-packages/zigpy/device.py", line 93, in request
    expect_reply=expect_reply,
  File "/config/deps/lib/python3.6/site-packages/bellows/zigbee/application.py", line 358, in request
    raise DeliveryError("Message send failure messagesend timeout")
zigpy.exceptions.DeliveryError: Message send failure messagesend timeout
```

During pairing i frequently pushed the button to ensure the sensor is not going to Sleep.

Can anyone help me out?

Regards
Richard

**Comment by iot7272** [comment]
Facing a similar issue with the Xiaomi door sensor. 
Also not able to retrieve endpoint and cluster information from command line bellows.

**Comment by Yoda-x** [comment]
can you please enable debugging and provide a full log. 
Also the zigbee.db would be helpful. Are you using my master branch?
Do you have other devices already connected and what are these? 

Many thanks

**Comment by darootler** [comment]
>           can you please enable debugging and provide a full log.
> Also the zigbee.db would be helpful. Are you using my master branch?
> Do you have other devices already connected and what are these?
> Many thanks

Hi,

I am using your master branch and i don't have any other devices connected. Please see the attached log and zigbee.db.

[home-assistant.log](https://github.com/Yoda-x/ha-zha-new/files/2721876/home-assistant.log)
[zigbee.zip](https://github.com/Yoda-x/ha-zha-new/files/2721877/zigbee.zip)

Regards
Richard

**Comment by darootler** [comment]
Seems that my Elelabs ZigBee Raspberry Pi Shield is defect.

Sorry and thank you guys.

Regards
Richard

**Comment by alex-v-g** [comment]
@darootler - I had similar problem with elelabs and raspberry pi2. Wanted already to send complains to elelabs, but decided to give a try with another pi. Bought pi3 and everything worked. Probably my GPIO controller was defect or not enough voltage on GPIO contacts. Try elelabs with somebody else's raspberry pi.

**Comment by darootler** [comment]
@alex-v-g 

An Elelabs employee already took a look at my problem via remote session. The adapter ahows up and communication in general is okay. He just offered a refund and said that he will try to reproduce my problem with the refunded Shield.

Regards
Richard

**Comment by KLUSEK** [comment]
Have you set flag "enable_uart=1" in your /boot/config.txt on raspberry 3?

Remember also to do not underclock the "core_freq"

**Comment by darootler** [comment]
According to [documentation from Elelabs](https://elelabs.com/downloads/EZBPIS_UG_2_HomeAssistant.pdf) the flag "dtoverlay=pi3-miniuart-bt" has to be set. I did not play around with core frequencies.

Do you think "enable_uart=1" is worth a try?

Regards
Richard

**Comment by KLUSEK** [comment]
I don't recall now, but it's related to fact that BT is on UART on RPi3, that's the reason of their suggestion.

I had to set enable_uart=1 to have a shield and the BT working properly together

**Comment by alex-v-g** [comment]
on RPi3 I just followed instruction from ELELABS. Can't remember any "enable_uart=1" in my setup. Everything works OK
