### ISSUE TITLE
zha-new suddenly stops...

### ISSUE THREAD

**Issue by MYeager1967** [Yoda-x/ha-zha-new#72]
I looked at my HA installation a bit ago and realized that zha-new was erroring out. This is the closest thing I can figure is causing it and I notice in the git repository, something was changed (looks like yesterday). I had to manually install files before with your help, but I don't remember how we did it.

Not initializing zha_new because could not install requirement https://github.com/Yoda-x/zigpy/archive/preview.zip#zigpy==0.1.4-Ypre

https://github.com/Yoda-x/zigpy/archive/preview.zip#zigpy==0.1.4-Ypre: HTTP error 404 while getting https://github.com/Yoda-x/zigpy/archive/preview.zip#zigpy==0.1.4-Ypre
  Could not install requirement https://github.com/Yoda-x/zigpy/archive/preview.zip#zigpy==0.1.4-Ypre because of error 404 Client Error: Not Found for url: https://codeload.github.com/Yoda-x/zigpy/zip/preview
Could not install requirement https://github.com/Yoda-x/zigpy/archive/preview.zip#zigpy==0.1.4-Ypre because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/Yoda-x/zigpy/zip/preview for URL https://github.com/Yoda-x/zigpy/archive/preview.zip#zigpy==0.1.4-Ypre
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by Yoda-x** [comment]
I did some cleanups of the preview branches.
Can you please switch/update your zha_new to the preview branch? This should fix it. 

Thanks

**Comment by MYeager1967** [comment]
I'm a git amatuer. How do I change it?

**Comment by MYeager1967** [comment]
I'll delete all the old files in a bit and try again. 🙂

**Comment by Yoda-x** [comment]
this version needs the newest hass >=0.86, so please update you hass installation.
Not sure what kind if installation you have ? plain install, venv, docker, hassio?

**Comment by Yoda-x** [comment]
where you able to get it running again?

**Comment by Yoda-x** [comment]
any news?

**Comment by MYeager1967** [comment]
I replied by email twice now, not sure why they aren't showing up. Everything is working perfectly again as far as zha-new is concerned.

**Comment by Yoda-x** [comment]
perfect, and many thanks
