### ISSUE TITLE
zha_new compatibility with zigpy-xbee & zigpy-deconz & zigpy-zigate or?

### ISSUE THREAD

**Issue by Hedda** [Yoda-x/ha-zha-new#73]
@Yoda-x is your zha_new also compatible with zigpy-xbee, zigpy-deconz, and zigpy-zigate?

- https://github.com/zigpy/zigpy-xbee
- https://github.com/zigpy/zigpy-deconz
- https://github.com/doudz/zigpy-zigate

Other than zigpy/bellows that is?

**Comment by Yoda-x** [comment]
Hi,
sorry, it only works for bellows. Which may caused by the fact, that I have only em35x usb sticks and non of the others.

**Comment by Hedda** [comment]
OK, that's cool, though FYI, Dresden-Elektronik might ship you a free ConBee if you ask manup here:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/158

Maybe the others would donate free hardware to you too if ask nicely and let know about your WIP.

**Comment by Yoda-x** [comment]
I can move over the support from upstrean zha. But as I don't have the hardware for testing or the time it would create more pain than use.  And support and development of zha is getting much better now. It's getting more and more usable with an active bunch of developers.
If you want to backport some of my code to zha. Feel free. It's free
