### ISSUE TITLE
HA 0.89 support

### ISSUE THREAD

**Issue by estevez-dev** [Yoda-x/ha-zha-new#77]
There is more changes related to custom_components are coming in Home Assistant 0.89 release: https://www.home-assistant.io/blog/2019/03/06/release-89/

**if you want to override a built-in platform, you will need to override the whole component.**

**Comment by Yoda-x** [comment]
hi,
 zha_new is not a build_in platform, it has a different name than zha. So this should not a problem.
We use the same modules in different versions. Where I'm thinking to rename bellows and zigpy, to have no interference...
