### ISSUE TITLE
Xiaomi temperature sensor appears in celsius?

### ISSUE THREAD

**Issue by kevinduong** [Yoda-x/ha-zha-new#78]
It appears that my temperature sensor is appearing in celsius. There's no possible way it's currently 14.3C but 57F makes more sense.

![image](https://user-images.githubusercontent.com/2790080/54325752-d412e400-45d1-11e9-8658-63e759043f81.png)

**Comment by Yoda-x** [comment]
Hi, do you set your HA to Fahrenheit?
The sensor provides Temperatur in celsius. So this would need to add a convert function.

**Comment by kevinduongcalabrio** [comment]
My unit_system is set to imperial and the unit_of_measurement is Fahrenheit.

If the sensor reports Fahrenheit as the unit_of_measurement, shouldn't it be Fahrenheit?

**Comment by Yoda-x** [comment]
Thanks for your feedback. I have some ideas where to tweak the code. Please stay tuned.

**Comment by Adminiuga** [comment]
@Yoda-x make temperature sensor Entity always return celsius for unit of measurement and then just use celsius for the state. Front end will convert temperature automatically to the system's unit of temp measurement.

**Comment by Yoda-x** [comment]
yepp, already in my dev tree and tested. I was unsure if there are sensors reporting in F. But the cluster library only mentions C. So that's an easy one.

**Comment by Yoda-x** [comment]
now on master
