### ISSUE TITLE
Can't connect WXKG01LM

### ISSUE THREAD

**Issue by sarkar-anwar** [Yoda-x/ha-zha-new#88]
Hi,
Your project is really great. It helped a lot to setup my system. I have a bunch of Aqara remotes model number WXKG01LM that I am having trouble connecting. Does your code support this switch? If so can you please help me connecting these switches?

**Comment by Yoda-x** [comment]
Hi,
the Aqara remotes are in general supported. It may be needed to link your model to the right device handler. can you provide your zigbee.db or the model name of the remote?

**Comment by sarkar-anwar** [comment]
[zigbee.db](https://drive.google.com/file/d/1Bmv-Oc8pCFMx546GXkaUjDH93Pocfekv/view?usp=sharing)

I bought the switches from here-
[Button](https://www.gearbest.com/smart-light-bulb/pp_257679.html?wid=1433363)

**Comment by sarkar-anwar** [comment]
Sorry, the switch was actually paired but did not show up immediately and with a weird name. So I thought it was not paired.

Closing.
