### ISSUE TITLE
Xiaomi water sensor not detecting water

### ISSUE THREAD

**Issue by sarkar-anwar** [Yoda-x/ha-zha-new#93]
Hi,
I am not sure if this is zha_new related or not. If not, please feel free to close it and point me to right direction. 

I bought some Xiaomi water sensors from [here](https://www.gearbest.com/home-smart-improvements/pp_668897.html?wid=1433363). They paired with the names like this- binary_sensor.binary_sensor_lumi_lumi_sensor_wleak_aq1_0281f51b_1, 

When I test them by putting some water on a plate and placing the sensors in the water, the sensor does not detect the water. I waited about 10 minutes for the sensor to change status. But when I press the button on top, the sensor update the status and detects water immediately. Same thing happens when I take them off the water and dry them. Also this is not due to defective sensor as I have about 8 of them and all of them are showing the same thing. 

is it possible that when the sensors detects water they use a different method of updating status comapred to the button press and that method is not being detected by zha_new?

**Comment by Yoda-x** [comment]
it's an issue with my code. please get the new master. It should work now.
thanks for pointing this out.

**Comment by sarkar-anwar** [comment]
Thanks for the quick fix. Do I need to pair the sensors again? Or just updating the code would work?

**Comment by Yoda-x** [comment]
just updating the code will work. The messages from the devices arrived already, they were just ignored.

**Comment by sarkar-anwar** [comment]
Looks to be working perfectly. Thanks a lot. Closing the issue.
