### ISSUE TITLE
Add device model names to topology map

### ISSUE THREAD

**Issue by mikeybeck** [Yoda-x/ha-zha-new#97]
I've made a [small edit to the zigbee2dot.py file](https://github.com/mikeybeck/ha-zha-new/commit/a4d3b02667de19569e77efe6cf94511786e261e9) which adds the device model names to the nodes in the topology map.  
It works fine with my network, but I only have a few devices so far.

If you're interested, can you please give it a try and let me know if you'd like me to make a PR?

**Comment by Yoda-x** [comment]
Hello,
sure, please create a PR. I was thinking sometime the same, just showing the nwk ids is not self explaining

**Comment by mikeybeck** [comment]
Done, thanks!
